server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://tracker-api:3000/api/;
    }

    location /api/health {
        proxy_pass http://tracker-api:3000/health;
    }
}